[package]
name = "clear-all-to-win-server"
version = "0.1.0"
authors = ["wcaokaze <wcaokaze@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
